ci:
  skip: ["zig-fmt", "zig-build-test", "zig-build"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ['--autofix']
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: mixed-line-ending
        args: ['--fix=lf']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: forbid-binary
      - id: markdownlint # Configure in .mdlrc
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.12
    hooks:
      - id: gitleaks
  - repo: https://github.com/batmac/pre-commit-zig
    rev: v0.2.1
    hooks:
      - id: zig-fmt
      - id: zig-build-test
      - id: zig-build
