name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: "0.10.0-dev.3004+397e6547a"

      - uses: nektro/actions-setup-zigmod@v1

      - run: zig version
      - run: zig env
      - run: zigmod version
      - run: zigmod ci
      - run: zig build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: "0.10.0-dev.3004+397e6547a"
      - run: zig fmt --check src/*.zig
