name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.0.1
        with:
          version: master

      - uses: nektro/actions-setup-zigmod@v1

      - run: zig version
      - run: zig env
      - run: zigmod version
      - run: zigmod ci
      - run: zig build
      - run: zig build test
      - run: ./zig-out/bin/ZencPipe -G

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2.0.1
        with:
          version: master
      - run: zig fmt --check .
